[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
handmade_naive = "2HWXfYcvZGR8MGrjAwn4JFiLHTptZF8ArPCNrCd8ZJKz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
